### ISSUE TITLE
hardkoded username

### ISSUE THREAD

**Issue by kblok** [kblok/kblok.github.io#5]
Hey @hardkoded this repo is for the hardkoded.com site. My twitter handle is also @hardkoded. 
You don't have your email public, mentioning you on an issue is the only way I have yo contact you.

As I don't see much public activity on your account. Would you be willing to release the hardkoded username?

![please](https://media1.giphy.com/media/I1nwVpCaB4k36/giphy.gif?cid=790b761116f9f68fd460670aa14a6a5d83d0646c7257ee5e&rid=giphy.gif)

**Comment by hardkodedold** [comment]
No problem mate.
I changed my password which I will send to your email and from today Hardkoded is yours. Change the password as soon as you can.
Good luck and enjoy!
